#!/usr/bin/python3
import sys
def factorize(n):
    for i in range(2, int(n ** 0.5) + 1):
        if n % i == 0:
            return (i, n // i)
    return None
def factor_file(filename):
    with open(filename, "r") as f:
        for line in f:
            n = int(line.rstrip())

            factors = factorize(n)
            if factors is not None:
                p, q = factors
                print(f"{n}={p}*{q}")

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: factors <file>")
        sys.exit(1)
    factor_file(sys.argv[1])